-- AlterTable
ALTER TABLE "Plan" ADD COLUMN     "contactsMax" INTEGER NOT NULL DEFAULT 200,
ADD COLUMN     "listsMax" INTEGER NOT NULL DEFAULT 2,
ADD COLUMN     "logRetentionDays" INTEGER NOT NULL DEFAULT 7,
ADD COLUMN     "priceAnnual" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "webhooks" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "workflowsMax" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "maxBulkSend" SET DEFAULT 0,
ALTER COLUMN "apiKeysMax" SET DEFAULT 1,
ALTER COLUMN "templatesMax" SET DEFAULT 3;
