// src/theme.js — Theme partagé entre Landing & Dashboard

export const T = {
  bg: "#f4f6f9",
  bgCard: "#ffffff",
  border: "#e2e6eb",
  text: "#1e293b",
  textSub: "#64748b",
  textMuted: "#94a3b8",
  primary: "#6366f1",
  primaryLight: "#eef0ff",
  primaryDark: "#4f46e5",
  success: "#22c55e",
  successLight: "#edfcf0",
  warning: "#f59e0b",
  warningLight: "#fffbeb",
  danger: "#ef4444",
  dangerLight: "#fef2f2",
  shadow: "0 1px 3px rgba(0,0,0,0.08)",
  shadowMd: "0 4px 12px rgba(0,0,0,0.08)",
  radius: 10,
};

export const styles = {
  card: {
    background: T.bgCard,
    border: `1px solid ${T.border}`,
    borderRadius: T.radius,
    boxShadow: T.shadow,
  },
  btn: {
    background: T.primary,
    color: "#fff",
    border: "none",
    padding: "10px 22px",
    borderRadius: 8,
    cursor: "pointer",
    fontSize: 14,
    fontWeight: 600,
    boxShadow: "0 2px 6px rgba(99,102,241,0.3)",
  },
  btnOutline: {
    background: "transparent",
    color: T.primary,
    border: `1.5px solid ${T.primary}`,
    padding: "9px 22px",
    borderRadius: 8,
    cursor: "pointer",
    fontSize: 14,
    fontWeight: 600,
  },
  btnSm: {
    background: T.primary,
    color: "#fff",
    border: "none",
    padding: "6px 14px",
    borderRadius: 6,
    cursor: "pointer",
    fontSize: 12,
    fontWeight: 600,
  },
  input: {
    padding: "9px 13px",
    border: `1px solid ${T.border}`,
    borderRadius: 8,
    fontSize: 13,
    color: T.text,
    outline: "none",
    background: "#fff",
    width: "100%",
    boxSizing: "border-box",
  },
};